services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:0heIG2gvNqiZ@ep-shrill-term-a52dpvs3-pooler.us-east-2.aws.neon.tech/PH-task?sslmode=require
